version: "3.3"
services:
  redash:
    # 選用此版本的 redash image
    image: redash/redash:10.1.0.b50633
    # depends 代表依賴關係
    # 需要等 postgres、redis 先架設完成
    # 才會開始架設 redash services
    depends_on:
      - postgres
      - redis
    restart: always
    # redash 啟動 server 指令
    command: server
    ports:
      - target: 5000
        published: 5000
        mode: host
    # 相關的環境變數，包含
    environment:
      PYTHONUNBUFFERED: 0
      # log 等級
      REDASH_LOG_LEVEL: INFO
      # redis 的連線設定
      REDASH_REDIS_URL: redis://redis:6379/0
      # postgres 的密碼
      POSTGRES_PASSWORD: postgres_password
      REDASH_COOKIE_SECRET: redash_cookie_secret
      REDASH_SECRET_KEY: redash_secret_key
      # postgres 的連線設定
      REDASH_DATABASE_URL: postgresql://postgres:postgres_password@postgres/postgres
      # 允許在 redash 上使用 python
      REDASH_ADDITIONAL_QUERY_RUNNERS: redash.query_runner.python
      # worker 數量
      # 這是做範例，設定 1，
      # 未來可根據需求自行增加
      REDASH_WEB_WORKERS: 3
    networks:
        - finmind_network

  create_table:
    # 相關設定與 redash services 相同
    # 也用相同的 image
    image: redash/redash:10.1.0.b50633
    depends_on:
      - postgres
      - redis
    command: python /app/manage.py database create_tables
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: INFO
      REDASH_REDIS_URL: redis://redis:6379/0
      POSTGRES_PASSWORD: postgres_password
      REDASH_COOKIE_SECRET: redash_cookie_secret
      REDASH_SECRET_KEY: redash_secret_key
      REDASH_DATABASE_URL: postgresql://postgres:postgres_password@postgres/postgres
      REDASH_ADDITIONAL_QUERY_RUNNERS: redash.query_runner.python
      REDASH_WEB_WORKERS: 1
    networks:
        - finmind_network

  scheduler:
    # 用於 redash 相關的 scheduler 排程
    image: redash/redash:10.1.0.b50633
    depends_on:
      - postgres
      - redis
    restart: always
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: INFO
      REDASH_REDIS_URL: redis://redis:6379/0
      POSTGRES_PASSWORD: postgres_password
      REDASH_COOKIE_SECRET: redash_cookie_secret
      REDASH_SECRET_KEY: redash_secret_key
      REDASH_DATABASE_URL: postgresql://postgres:postgres_password@postgres/postgres
      REDASH_ADDITIONAL_QUERY_RUNNERS: redash.query_runner.python
      QUEUES: "celery"
      WORKERS_COUNT: 3
    networks:
        - finmind_network
  
  scheduled_worker:
    # 分散式中的 worker 
    image: redash/redash:10.1.0.b50633
    depends_on:
      - postgres
      - redis
    restart: always
    command: worker
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: INFO
      REDASH_REDIS_URL: redis://redis:6379/0
      POSTGRES_PASSWORD: postgres_password
      REDASH_COOKIE_SECRET: redash_cookie_secret
      REDASH_SECRET_KEY: redash_secret_key
      REDASH_DATABASE_URL: postgresql://postgres:postgres_password@postgres/postgres
      REDASH_ADDITIONAL_QUERY_RUNNERS: redash.query_runner.python
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 3
    networks:
        - finmind_network

  adhoc_worker:
    image: redash/redash:10.1.0.b50633
    depends_on:
      - postgres
      - redis
    restart: always
    command: worker
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: INFO
      REDASH_REDIS_URL: redis://redis:6379/0
      POSTGRES_PASSWORD: postgres_password
      REDASH_COOKIE_SECRET: redash_cookie_secret
      REDASH_SECRET_KEY: redash_secret_key
      REDASH_DATABASE_URL: postgresql://postgres:postgres_password@postgres/postgres
      REDASH_ADDITIONAL_QUERY_RUNNERS: redash.query_runner.python
      QUEUES: "queries"
      WORKERS_COUNT: 3
    networks:
        - finmind_network

  redis:
    # redis 資料庫
    image: redis:5.0
    restart: always
    volumes:
      - redis-redash:/bitnami/redis/data
    networks:
        - finmind_network

  postgres:
    # postgres 資料庫
    image: postgres:9.6-alpine
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: INFO
      REDASH_REDIS_URL: redis://redis:6379/0
      POSTGRES_PASSWORD: postgres_password
      REDASH_COOKIE_SECRET: redash_cookie_secret
      REDASH_SECRET_KEY: redash_secret_key
      REDASH_DATABASE_URL: postgresql://postgres:postgres_password@postgres/postgres
      REDASH_ADDITIONAL_QUERY_RUNNERS: redash.query_runner.python
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    networks:
        - finmind_network

  nginx:
    # 網頁伺服器
    image: redash/nginx:latest
    depends_on:
      - redash
    restart: always
    networks:
        - finmind_network

networks:
  finmind_network:
    external: true
    
volumes:
  postgres:

  redis-redash:

