import os

FINMIND_API_TOKEN = os.environ.get("FINMIND_API_TOKEN", "")
REDASH_MYSQL_DATA_HOST = os.environ.get("REDASH_MYSQL_DATA_HOST", "")
REDASH_MYSQL_DATA_USER = os.environ.get("REDASH_MYSQL_DATA_USER", "")
REDASH_MYSQL_DATA_PASSWORD = os.environ.get("REDASH_MYSQL_DATA_PASSWORD", "")
REDASH_MYSQL_DATA_PORT = int(os.environ.get("REDASH_MYSQL_DATA_PORT", 3306))
REDASH_MYSQL_DATA_DATABASE = os.environ.get("REDASH_MYSQL_DATA_DATABASE", "")
SCHEDULER_PASSWORD = os.environ.get("SCHEDULER_PASSWORD", "finmind")

MESSAGE_QUEUE_TYPE = os.environ.get("MESSAGE_QUEUE_TYPE", "127.0.0.1")
MESSAGE_QUEUE_HOST = os.environ.get("MESSAGE_QUEUE_HOST", "127.0.0.1")
MESSAGE_QUEUE_PORT = int(os.environ.get("MESSAGE_QUEUE_PORT", "6379"))
MESSAGE_QUEUE_USER = os.environ.get("MESSAGE_QUEUE_USER", "test")
MESSAGE_QUEUE_PASSWORD = os.environ.get("MESSAGE_QUEUE_PASSWORD", "test")
MESSAGE_QUEUE_DB = os.environ.get("MESSAGE_QUEUE_DB", "7")
